---
- name: Install chrony
  ansible.builtin.dnf:
    name: chrony
    state: present

- name: Enable and start chrony
  ansible.builtin.systemd_service:
    name: chronyd.service
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
...
